"""add task assignment and updated_at

Revision ID: 0cd1d547d8f0
Revises: d4af186074e4
Create Date: 2026-02-23 05:26:17.701958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd1d547d8f0'
down_revision: Union[str, Sequence[str], None] = 'd4af186074e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assigned_to', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_tasks_assigned_to', 'tasks', ['assigned_to'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index('ix_tasks_assigned_to', table_name='tasks')
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'assigned_to')
    # ### end Alembic commands ###
