"""add projects

Revision ID: 2f310cefb404
Revises: 21cbd00986cb
Create Date: 2026-02-18 17:26:43.498907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f310cefb404'
down_revision: Union[str, Sequence[str], None] = '21cbd00986cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_org_user'), table_name='org_members')
    op.drop_index(op.f('idx_user_id'), table_name='org_members')
    op.create_index('ix_org_user', 'org_members', ['org_id'], unique=False)
    op.create_index('ix_user_id', 'org_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_id', table_name='org_members')
    op.drop_index('ix_org_user', table_name='org_members')
    op.create_index(op.f('idx_user_id'), 'org_members', ['user_id'], unique=False)
    op.create_index(op.f('idx_org_user'), 'org_members', ['org_id'], unique=False)
    # ### end Alembic commands ###
